// Pastoral descriptions for worship key browse pages.
export const keyDescriptions = {
  "g": "The key of G is the most widely used key in contemporary worship. Its open chord shapes on guitar feel natural under the hands of acoustic players, and its vocal range sits comfortably in the middle register where most congregations find their voice. From intimate acoustic gatherings to large arena worship nights, songs in G have a warmth and accessibility that invites everyone in the room to sing. This key has become the common language of modern praise.",
  "d": "The key of D carries centuries of sacred music in its bones. D major has long been the key of declaration and grandeur — full-bodied, resonant, and distinctly noble in character. Songs in D often feel larger than themselves, as if the key itself opens the lungs and lifts the eyes. On guitar the open D chord rings with a richness that drives congregational singing forward, and on piano the voicings have a regal quality that suits both hymns and contemporary worship.",
  "a": "Bright, joyful, and energetic — the key of A is a celebration key. It sits a step higher than G, giving it an added lift and vitality that works beautifully for upbeat, high-energy worship. The key has a natural brightness that suits songs of victory, praise, and exultant joy. Worship leaders working in A will find it propels congregational voices upward, making it excellent for moments of high praise and energetic celebration.",
  "e": "The key of E is where electric guitar-led worship finds its natural home. The open low E string resonates through the entire mix, giving songs a roaring, powerful quality that few other keys match. E major worship songs often feel anthemic and expansive, with a sonic weight that suits large-room worship settings. Its distinctive sound signals to the congregation that something significant is about to happen.",
  "c": "The key of C is the musician's mother tongue — no sharps, no flats, the clean slate of all Western harmony. For keyboard-led worship, C is supremely accessible and reads clearly on any lead sheet. Songs in C have a straightforward clarity and openness that makes them easy to learn and easy to sing. In the right hands, C communicates a refreshing simplicity that suits songs of pure, unadorned devotion.",
  "f": "Warm, intimate, and slightly understated, the key of F holds a special place in the worship repertoire. It sits in a comfortable register that suits many natural singing voices, and its chord voicings have a richness and roundness that many other keys don't match. Songs in F often carry a more introspective, tender quality — found in quieter moments of a worship set, slower builds into God's presence, or songs of personal prayer and surrender.",
  "bb": "Bb major is the key of the hymnal and the key of congregational singing at its most natural and full. It sits beautifully in the middle of the human vocal range and has a fullness and warmth that makes even a modestly sized congregation sound like a great choir. Many of the great hymns of the faith live in Bb, and contemporary worship songs in this key tend to carry a similar communal richness. It is a key built for the room, not just the stage.",
  "eb": "The key of Eb carries a warmth and fullness that makes it a favorite in gospel and R&B-influenced worship. It suits rich vocal harmonies beautifully, and brass instruments find their natural home in Eb. Songs written here often feel lush and deeply emotive, with a harmonic richness that rewards full instrumentation. Worship drawn from gospel, soul, or charismatic traditions will find Eb a natural and resonant choice.",
  "ab": "The key of Ab has a particular lushness and depth that sets it apart in the worship landscape. It suits songs of deep reverence, sustained praise, and contemplative worship. Ab is frequently found in contemporary gospel and in worship music that emphasizes the weightiness of God's glory — songs that build slowly and majestically toward a climax of adoration.",
  "b": "Bright, uplifting, and slightly uncommon, the key of B has a distinctive quality that makes worship songs here stand out. It carries a shimmer on piano and an anthemic quality that suits bold declarations of faith. Songs in B often feel fresh and adventurous, stepping away from more familiar worship keys into territory that gives arrangements a lift and freshness that engages the congregation in an invigorating way.",
  "f-sharp": "The key of F# has a bright, crystalline quality that gives worship songs a distinctive shimmer and energy. When used intentionally, F# creates an atmosphere of heightened joy and celebratory brightness. On piano the chord voicings feel full and resonant, lending themselves particularly well to fast, upbeat praise songs that communicate an almost irrepressible joy.",
  "db": "The key of Db is one of the most emotionally evocative in the worship catalog. Richly resonant on piano where it opens up lush, full chord voicings, songs in Db often carry a particular depth and weight — frequently slower and more contemplative, built for moments of deep and unhurried worship. When a set needs to go slow into God's presence, Db creates that holy atmosphere most naturally.",
  "gb": "Gb and F# are enharmonically identical, sharing the same bright, full-bodied character. On piano, Gb opens up voicings that feel particularly rich and full. It suits strong tenor and soprano voices well, and worship sets that reach for Gb signal an intention toward high, soaring praise that lifts the congregation's eyes and voices upward.",
  "em": "E minor is one of the most emotionally honest keys in the worship library. Where major keys celebrate and declare, E minor holds space for the complexity of the Christian life — the longing, the lament, the ache of waiting, and the hope that persists through darkness. Songs in Em lean into tension and find God faithful in the midst of it, giving congregations permission to bring their whole selves to worship.",
  "gm": "G minor is a key of deep feeling and searching beauty. It carries an emotional complexity that major keys cannot access — a bittersweet quality, a reaching toward something just out of grasp. Worship in Gm creates space for the full range of human spiritual experience: lament and longing, confession and the cry for mercy, the tender intimacy of a soul that has stopped performing and simply come as it is.",
  "c-sharp": "C# major has a bright, crystalline quality that gives worship songs a distinctive shimmer and energy. When used intentionally, C# creates an atmosphere of heightened joy and celebratory brightness. On piano the voicings feel full and resonant, lending themselves particularly well to upbeat praise songs that communicate an irrepressible joy and vitality."
};

export function getKeyDescription(key) {
  return keyDescriptions[key] || null;
}
